### ISSUE TITLE
useHoverIntent return wrong array methods

### ISSUE THREAD

**Issue by kurdin** [natelindev/react-use-hoverintent#38]
Your hook is not working if you follow the documentation. In your source code you return `[isHovering, setIsHovering, intentRef]` from useHoverIntent hook but in the doc, it says `[isHovering, ref]`. 
`ref` is not working correctly because it's setIsHovering method.

**Comment by tony** [comment]
`const [isHovering, setIsHovering, intentRef]` did the trick for me (as of 1.2.8)

This package is really nice though, nice job @natelindev!

**Comment by kurdin** [comment]
> `const [isHovering, setIsHovering, intentRef]` did the trick for me (as of 1.2.8)
> 
> This package is really nice, nice job @natelindev!

Yes it does work good with  `const [isHovering, setIsHovering, intentRef]` I wanted to point that docs need to be updated as well.

Indeed nice package @natelindev

**Comment by natelindev** [comment]
Sorry for not updating the docs and introducing (potentially)breaking change with incorrect version change.
I'll create a new version that fix these issues.

**Comment by natelindev** [comment]
fixed in v1.2.9
